# Configuration - Assistant MJ Les Lames du Cardinal

# Chemins (relatifs au répertoire de l'application)
paths:
  base_dir: "."  # Répertoire de l'application (où se trouve app.py)
  pdf_root: "Data"  # Dossier Data dans le répertoire de l'application
  char_dir: "Characters"  # Dossier Characters dans le répertoire de l'application
  db_dir: "lames_db"  # Base vectorielle dans le répertoire de l'application
  save_dir: "saved_sessions"  # Sessions sauvegardées
  memory_dir: "memory"  # Mémoire persistante

# Configuration du modèle
model:
  default: "mistral-nemo"
  temperature: 0.0
  top_p: 1.0
  fallback_models:
    - "llama3"
    - "mistral"
    - "phi3"

# Configuration RAG
rag:
  embedding_model: "all-MiniLM-L6-v2"
  k_retrieval: 6
  chunk_size: 1000
  chunk_overlap: 150
  use_cuda: true  # Tente d'utiliser CUDA si disponible

# Configuration de la mémoire
memory:
  max_mj_memory: 30  # Nombre max d'échanges à garder en mémoire MJ
  max_encyclo_memory: 10  # Nombre max pour mode encyclopédique
  short_memory_context: 3  # Nombre d'échanges récents à inclure dans le prompt

# Configuration UI
ui:
  default_mode: "MJ immersif"  # ou "Encyclopédique"
  show_sources_default: false
  timeline_enabled: true
  auto_save_interval: 5  # Sauvegarde auto tous les N messages

# Prompts (peuvent être personnalisés)
prompts:
  mj_system: |
    Tu es le Maître de Jeu des Lames du Cardinal.
    Tu dois répondre **uniquement** à partir des extraits fournis ci-dessous.
    Si l'information n'existe pas dans le contexte, réponds exactement : "Aucune information trouvée dans le corpus."
    N'invente JAMAIS d'informations.
    
  encyclo_system: |
    Tu es une encyclopédie des RÈGLES du jeu 'Les Lames du Cardinal'.

    IMPÉRATIF : Tu dois répondre UNIQUEMENT sur les RÈGLES DE JEU (mécaniques, Tarot des Ombres, combat, compétences, etc.).

    IGNORE COMPLÈTEMENT :
    - Les éléments narratifs et d'univers
    - Les descriptions de personnages ou lieux
    - Les intrigues et scénarios
    - Tout ce qui n'est pas une RÈGLE DE JEU MÉCANIQUE

    Si la question porte sur l'univers/narration, réponds : "Je ne réponds qu'aux questions sur les RÈGLES du jeu. Pour des questions d'univers, utilise le mode MJ immersif."

    Si aucune règle n'est trouvée dans les extraits fournis, réponds : "Aucune règle trouvée sur ce sujet dans le corpus."

    Réponds de manière factuelle, précise et concise. Cite les numéros de page si disponibles.

# Options avancées
advanced:
  max_pdf_pages: 500  # Limite de pages par PDF pour éviter les timeouts
  enable_statistics: true  # Active les statistiques de session
  export_format: "markdown"  # markdown ou pdf